// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs8IqXcUooymAIRl0Vp7ZT2ZsDZWYO7PY',
    appId: '1:534533412946:web:1aa991d7345af41a2ce78b',
    messagingSenderId: '534533412946',
    projectId: 'my-exam-777',
    authDomain: 'my-exam-777.firebaseapp.com',
    storageBucket: 'my-exam-777.appspot.com',
    measurementId: 'G-9GBT2GDVZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrNriAgnJuJbfHB_IpwOc9CG1gtRQV6XM',
    appId: '1:534533412946:android:1628abd6f572a7442ce78b',
    messagingSenderId: '534533412946',
    projectId: 'my-exam-777',
    storageBucket: 'my-exam-777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKnrj31F3dXsEZ0HeOXUDVO1uc3Twtow',
    appId: '1:534533412946:ios:de2c90348f2a0e732ce78b',
    messagingSenderId: '534533412946',
    projectId: 'my-exam-777',
    storageBucket: 'my-exam-777.appspot.com',
    androidClientId:
        '534533412946-bcb9p84caaaborp0efrhu64p6l71p67s.apps.googleusercontent.com',
    iosClientId:
        '534533412946-1sisg1lod147pr03fr3h262obfg17vv1.apps.googleusercontent.com',
    iosBundleId: 'com.krmeiirbek.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKnrj31F3dXsEZ0HeOXUDVO1uc3Twtow',
    appId: '1:534533412946:ios:cdacc7ee585a93cb2ce78b',
    messagingSenderId: '534533412946',
    projectId: 'my-exam-777',
    storageBucket: 'my-exam-777.appspot.com',
    androidClientId:
        '534533412946-bcb9p84caaaborp0efrhu64p6l71p67s.apps.googleusercontent.com',
    iosClientId:
        '534533412946-svau2sba45s1vajl4835rrpk7m0ei6um.apps.googleusercontent.com',
    iosBundleId: 'com.krmeiirbek.educationApp.RunnerTests',
  );
}
